spring.application.name=EventReservationApp
spring.datasource.url=jdbc:postgresql://localhost:5432/EventReservationApp
server.port=9090
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=yourVeryLongSecretKeyThatIsAtLeast256BitsLongForHS512Algorithm
# 24 hours
app.jwt.access-token-expiration-ms=86400000
# 7 days
app.jwt.refresh-token-expiration-ms=604800000